apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-437203
  artifacts:
    # - image: hudaprasetyo/auth
    # - image: asia-southeast2-c-docker.pkg.dev/ticketing-dev-437203/hudaprasetyo/auth
    - image: asia.gcr.io/ticketing-dev-437203/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
