apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # image: hudaprasetyo/auth
          # image: asia-southeast2-c-docker.pkg.dev/ticketing-dev-437203/hudaprasetyo/auth
          image: asia.gcr.io/ticketing-dev-437203/auth
          # imagePullPolicy: Never
          env:
            - name: APP_DATA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-secret-data
                  key: TICKETING_APP_DATA_SECRET_KEY
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ticketing-jwt-secret
                  key: TICKETING_JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
